// <auto-generated />
using Kutuphane.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kutuphane.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260616204442_AddYazarTable")]
    partial class AddYazarTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kutuphane.Model.Kategori", b =>
                {
                    b.Property<int>("KategoriNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriNo"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriNo");

                    b.ToTable("Kategoris");
                });

            modelBuilder.Entity("Kutuphane.Model.Kitap", b =>
                {
                    b.Property<int>("KitapNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KitapNo"));

                    b.Property<int>("KategoriNo")
                        .HasColumnType("int");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("KitapSayisi")
                        .HasColumnType("int");

                    b.Property<int>("YazarNo")
                        .HasColumnType("int");

                    b.HasKey("KitapNo");

                    b.HasIndex("KategoriNo");

                    b.HasIndex("YazarNo");

                    b.ToTable("Kitaps");
                });

            modelBuilder.Entity("Kutuphane.Model.Yazar", b =>
                {
                    b.Property<int>("YazarNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YazarNo"));

                    b.Property<string>("YazarAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("YazarNo");

                    b.ToTable("Yazars");
                });

            modelBuilder.Entity("Kutuphane.Model.Kitap", b =>
                {
                    b.HasOne("Kutuphane.Model.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kutuphane.Model.Yazar", "Yazar")
                        .WithMany("Kitaps")
                        .HasForeignKey("YazarNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("Kutuphane.Model.Yazar", b =>
                {
                    b.Navigation("Kitaps");
                });
#pragma warning restore 612, 618
        }
    }
}
