// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciSistemi.Models;

#nullable disable

namespace OgrenciSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OgrenciSistemi.Models.Bolum", b =>
                {
                    b.Property<int>("BolumNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumNo"));

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BolumNo");

                    b.ToTable("Bolums");
                });

            modelBuilder.Entity("OgrenciSistemi.Models.Ders", b =>
                {
                    b.Property<int>("DersNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersNo"));

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DersKredi")
                        .HasColumnType("int");

                    b.HasKey("DersNo");

                    b.ToTable("Derss");
                });

            modelBuilder.Entity("OgrenciSistemi.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciNo"));

                    b.Property<int>("BolumNo")
                        .HasColumnType("int");

                    b.Property<int>("BolumNo1")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenciSinif")
                        .HasColumnType("int");

                    b.HasKey("OgrenciNo");

                    b.HasIndex("BolumNo1");

                    b.ToTable("Ogrencis");
                });

            modelBuilder.Entity("OgrenciSistemi.Models.Ogretmen", b =>
                {
                    b.Property<int>("OgretmenNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgretmenNo"));

                    b.Property<int>("BolumNo")
                        .HasColumnType("int");

                    b.Property<int>("BolumNo1")
                        .HasColumnType("int");

                    b.Property<string>("OgretmenAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgretmenBrans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgretmenNo");

                    b.HasIndex("BolumNo1");

                    b.ToTable("Ogretmens");
                });

            modelBuilder.Entity("OgrenciSistemi.Models.Ogrenci", b =>
                {
                    b.HasOne("OgrenciSistemi.Models.Bolum", "bolum")
                        .WithMany()
                        .HasForeignKey("BolumNo1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bolum");
                });

            modelBuilder.Entity("OgrenciSistemi.Models.Ogretmen", b =>
                {
                    b.HasOne("OgrenciSistemi.Models.Bolum", "bolum")
                        .WithMany()
                        .HasForeignKey("BolumNo1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bolum");
                });
#pragma warning restore 612, 618
        }
    }
}
